name: Deploy CD Pipelin

on:
    push:
        branches: ['main']

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Connect to Virtual Machine using SSH and deploy the application
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd ./fastapi
                git pull origin main
                sudo docker stop fastapi-app || true && sudo docker rm fastapi-app || true
                sudo docker build -t fastapi-app .
                sudo docker run --name fastapi-app -p 8000:8000 fastapi-app
                sudo nginx -s reload
